# Generated by Django 4.1.4 on 2022-12-17 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SRHR', 'SRHR'), ('H&G', 'H&G'), ('HIV/TB', 'HIV/TB'), ('WLPR', 'WLPR'), ('SILU', 'SILU')], max_length=200, verbose_name='Thematic Area')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Donor')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('info', models.TextField(blank=True, null=True)),
                ('person_responsible', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100, verbose_name='Enter Frequency')),
                ('project_start', models.DateField(default=django.utils.timezone.now)),
                ('project_end', models.DateField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('Ksh', 'Ksh')], max_length=100, null=True, verbose_name='Choose Currency')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me_system.thematic')),
            ],
        ),
    ]
